name: private_notes
description: A new Flutter project.

publish_to: 'none' 

version: 2.0.0+0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  image_picker: ^0.8.5+3
  hive: ^2.2.3
  auto_route: ^5.0.1
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  cupertino_icons: ^1.0.2
  day_night_switcher: ^0.2.0+1
  flag: ^6.0.0
  dynamic_themes: ^1.1.0
  getwidget: ^3.0.1
  fluttertoast: ^8.0.9
  flutter_slidable: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.15
  flutter_animate: ^1.0.0
  package_info_plus: ^2.0.0
  url_launcher: ^6.1.6
  simple_animations: ^5.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.1.11
  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/onboard_images/